language: node_js
node_js: 14

install: skip
script: skip

jobs:
  include:
    - stage: build
      os: linux
      install: yarn
      script: yarn build
      workspaces:
        create:
          name: shared
          paths:
            - node_modules
            - target
            - typings
            - flow-typed
            - docs

    - &test
      stage: test
      os: linux
      install: skip
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - npm run test:report
      after_script:
        - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      workspaces:
        use: shared

    - <<: *test
      if: type = pull_request
      os: windows
      workspaces:
      env: YARN_GPG=no
      install: yarn
      before_script: skip
      script: yarn test:unit
      after_script: skip

    - stage: release
      if: branch = master AND type != pull_request
      node_js: 14
      workspaces:
        use: shared
      install: skip
      script: npx -p @qiwi/semrel-toolkit semrel -e @qiwi/semrel-config
